### ISSUE TITLE
feature request - hpe-csi-driver 2.0.0 : add storage backend value for secret

### ISSUE THREAD

**Issue by bwgartner** [rancher/partner-charts#172]
Per partner [deployment](https://scod.hpedev.io/csi_driver/deployment.html#secret_parameters) 2.0.0 documentation, one needs to add a specific parameter, in secret, to connect to the server providing the storage backend. While the existing chart can be deployed without that, the actual use of the CSI/StorageClass needs this to be completely functional.

So, if possible, can this "value" be added to the webUI as a parameter (or at minimum called out in doc/UI)  to integrate into the kind: StorageClass (where templates were available for previous versions, but still unsure how those were even leveraged before).

**Comment by datamattsson** [comment]
Managing and referencing StorageClasses and Secrets is out scope for a CSI driver Helm chart.
