### ISSUE TITLE
Dynatrace OneAgent Operator is deprecated

### ISSUE THREAD

**Issue by lopf** [rancher/partner-charts#399]
According to https://github.com/Dynatrace/helm-charts#dynatrace-oneagent-operator-chart, the OneAgent Operator deployed in this chart is _deprecated_.
The new chart is here: https://github.com/Dynatrace/dynatrace-operator/tree/master/config/helm/chart/default
Can you update your partner charts or at least remove it?

**Comment by gregfurman** [comment]
Bump. Following the docs provided by Rancher, we almost used rolled out a and deprecated and unsupported deployment.

**Comment by nflondo** [comment]
Dynatrace OneAgent Operator was replaced with the new Dynatrace Operator in partner-charts back in Aug 2022.  Only the [new Dynatrace Operator](https://github.com/rancher/partner-charts/commit/313642f0630c0bfa6eb969fddaa8fc325c558fa3) is available in Rancher Apps partner catalog.  Closing.
