### ISSUE TITLE
Deprecate HPE FlexVolume Driver for Kubernetes

### ISSUE THREAD

**Issue by datamattsson** [rancher/partner-charts#482]
There are no instructions on how to remove an entry. HPE FlexVolume Driver for Kubernetes is deprecated and not supported by HPE.

If possible, mark Rancher 2.2.0 as rancher_max_version on all releases.

**Comment by atrendafilov** [comment]
Hello @datamattsson ,

I wanted to check if this issue is still active?
Could you please provide an update on the current status? It would be greatly appreciated.

Thank you for your attention.

**Comment by datamattsson** [comment]
I believe my particular issue has been fixed as I can't see the entry in the latest partner-charts on Rancher 2.7.3. Thank you!
