### ISSUE TITLE
Kasten K10 version 5.5.5 automatic update

### ISSUE THREAD

**Issue by akankshakumari393** [rancher/partner-charts#670]
After migration, the new version of charts were expected to be automatically pulled, But we don't see Kasten k10 version 5.5.5 in `index.yaml` of the repo. Do we need to make some extra changes?

**Comment by akankshakumari393** [comment]
cc @nflondo

**Comment by nflondo** [comment]
The CI only runs a couple of times a week, so if you released the new version in between this time you won't see it until CI runs again.  I'll run it today and it should grab k10 v 5.5.5

**Comment by akankshakumari393** [comment]
Thanks @nflondo, that make sense. the new version is now listed on the index. I will close the issue.

**Comment by akankshakumari393** [comment]
The Issue got resolved after next CI run.
