### ISSUE TITLE
Case sensitivity issue cloning repo to Mac

### ISSUE THREAD

**Issue by datamattsson** [rancher/partner-charts#700]
```
$ git clone https://github.com/rancher/partner-charts/
Cloning into 'partner-charts'...
remote: Enumerating objects: 28235, done.
remote: Counting objects: 100% (1725/1725), done.
remote: Compressing objects: 100% (1034/1034), done.
remote: Total 28235 (delta 628), reused 1638 (delta 613), pack-reused 26510
Receiving objects: 100% (28235/28235), 98.61 MiB | 23.99 MiB/s, done.
Resolving deltas: 100% (13893/13893), done.
Updating files: 100% (8980/8980), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'charts/gopaddle/gopaddle/README.md'
  'charts/gopaddle/gopaddle/readme.md'
```

**Comment by nflondo** [comment]
Hello @gopaddle-io, it looks like there is a duplicate [readme.md](https://github.com/rancher/partner-charts/tree/main-source/charts/gopaddle/gopaddle) in your gopaddle chart, would you be able to take a look at this issue?
Regards.

**Comment by gopaddle-io** [comment]
We have `app-readme.md` and `readme.md` under partner-charts/packages/gopaddle/gopaddle-lite/overlay. Should we remove one of these ?

**Comment by nflondo** [comment]
Yes, removing partner-charts/packages/gopaddle/gopaddle-lite/overlay/readme.md should take care of this issue.

**Comment by gopaddle-io** [comment]
@nflondo Can we please close this PR ? Redundant readme file has been removed as a part of this PR https://github.com/rancher/partner-charts/pull/720
