### ISSUE TITLE
Dkube wrong Icon URL 

### ISSUE THREAD

**Issue by nicholasSUSE** [rancher/partner-charts#721]
Hi I am on the **Mapps** team and have been working on the task of resolving [404s at the Chart Marketplace](https://github.com/rancher/rancher/issues/33778)

I have traced the issue and realized that the problem is because of a wrong URL inserted and approved in the following PR Commit:
https://github.com/rancher/partner-charts/pull/454/commits/a08b0e17118926f61b8ffa15e1c5f05e1bbbe7b0
![image](https://user-images.githubusercontent.com/127259813/232138407-62fbb632-97db-4a72-bce7-579074e8bbd9.png)

### Currently, the only 404 response we are getting is from Dkube:
![image](https://user-images.githubusercontent.com/127259813/232137599-fc47a048-b17d-4a12-968b-d4bc90105547.png)

cURL request for making debugging easier, you will have to replace the cookies with yours:`curl 'https://localhost:8443/v1/catalog.cattle.io.clusterrepos/rancher-partner-charts?chartName=dkube-deployer&link=icon&version=1.0.602' \
  -H 'Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: R_PCS=light; R_LOCALE=en-us; R_REDIRECTED=true; R_USERNAME=admin; R_THEME=dark; CSRF=0f82d1f94dec5cdeba4397078a69906a; R_SESS=token-7xmb8:kbzwqjjf8w9hp9z7d8888drfj25t7bvjcndtlgg875l67cwbdftbpv' \
  -H 'Referer: https://localhost:8443/dashboard/c/local/apps/charts' \
  -H 'Sec-Fetch-Dest: image' \
  -H 'Sec-Fetch-Mode: no-cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --compressed \
  --insecure`

As far as I know, the responsibility for this information is from the chart owner (dkube). I will leave 2 examples here from other rancher partner charts so someone can correct the issue:

- https://github.com/rancher/partner-charts/pull/564/commits/aa41b0c44aad48c67ca4b98231ce1aa6618574e4#diff-9776fa91576631cdee0fce6be81de074943919efb6959b34c1de91e06ab86377
- https://github.com/rancher/partner-charts/pull/577/commits/e1bae6090daca60e6e4061673fc1de9e7121a31d#diff-835dbad89d11109b1877547c71b00f2eba2d9625509c68edc295ecc4c880af70

In these examples all Chart.yaml files have a functioning icon URL.

**Comment by nflondo** [comment]
I've created an [issue ](https://github.com/oneconvergence/dkube-helm/issues/28)with dkube.  Will work with them in fixing this issue.

**Comment by nflondo** [comment]
Hi @nicholasSUSE my testing shows kdube icon url is working now.
![dkube-displaying-icon](https://user-images.githubusercontent.com/11321470/234343997-9ec4a1fb-145e-4fff-afb4-2545d30faf54.JPG)
