### ISSUE TITLE
Remove deprecated and hidden applications from Apps partner catalog

### ISSUE THREAD

**Issue by nflondo** [rancher/partner-charts#915]
As part of a clean up of Apps partner catalog, we've identified the following applications that are deprecated and hidden in the partner catalog:

- [Dynatrace Oneagent Operator](https://github.com/rancher/partner-charts/tree/main-source/charts/dynatrace/dynatrace-oneagent-operator)
- [Flexvolume Driver](https://github.com/rancher/partner-charts/tree/main-source/charts/hpe/hpe-flexvolume-driver)
- [SoftIron Ceph RBD](https://github.com/rancher/partner-charts/tree/main-source/charts/softiron/ceph-csi-rbd)
- [Sources for Amazon Web Services](https://github.com/rancher/partner-charts/tree/main-source/charts/aws-event-sources/aws-event-sources)

The above applications have been hidden/unavailable in Apps partner catalog for over 1 year and will be removed from partner-charts repo and no longer offered in the catalog.

**Comment by recena** [comment]
@nflondo Since the PR is already merged. We should close this issue.
