### ISSUE TITLE
Health-check of Emissary-Ingress

### ISSUE THREAD

**Issue by recena** [rancher/partner-charts#919]
This issue aims to perform a health check of this application.

| Attribute      |  Value                                                    |
| -------------- | --------------------------------------------------------- |
| Application    |  [Emissary-Ingress](https://www.getambassador.io/products/api-gateway)|             
| Vendor         |  [Ambassador Labs](https://www.getambassador.io)          |
| Contact Info.  | ???                                                       |
| Documentation. | https://www.getambassador.io/docs/emissary                |
| SCM            | https://github.com/emissary-ingress/emissary              |
| Helm Charts    | https://github.com/emissary-ingress/emissary/tree/master/charts/emissary-ingress |

- We want to contact with the vendor and ensure they are still interested on having this apps into the catalog.
- If they are interested, work together with them to review the recipes.

📔 There are no updates of this application (in the catalog) in **the last 12 months**.

#### Acceptance criteria

- [x] There is an email thread or GitHub thread (comments) with the vendor
- [x] We have identified a contact person
- [x] The recipes are updated or deprecated according to their interest.

**Comment by recena** [comment]
It seems the [current recipe](https://github.com/rancher/partner-charts/blob/main-source/charts/ambassador/ambassador/Chart.yaml) is obsolete or deprecated.

**Comment by recena** [comment]
In the current recipe, there are three maintainers (from datawire.io, former company name):

- email: flynn@datawire.io
- email: nkrause@datawire.io
- email: lukeshu@datawire.io

**Comment by recena** [comment]
@cakuros Are you still involved in ambassador.io?

**Comment by nflondo** [comment]
> * email: [flynn@datawire.io](mailto:flynn@datawire.io)
> * email: [nkrause@datawire.io](mailto:nkrause@datawire.io)
> * email: [lukeshu@datawire.io](mailto:lukeshu@datawire.io)

Email sent to the above email addresses resulted in "Undeliverable" response.

**Comment by recena** [comment]
@nflondo My suggestion is to remove it from the catalog. If they have new apps, we can consider to add them in the future.

**Comment by nflondo** [comment]
Done. PR #926
