### ISSUE TITLE
Health check of Dkube

### ISSUE THREAD

**Issue by nflondo** [rancher/partner-charts#923]
This issue aims to perform a health check of this application.

| Attribute      |  Value                                                    |
| -------------- | --------------------------------------------------------- |
| Application    |  Dkube Deployer |             
| Vendor         |  [Dkube](https://www.dkube.io/)          |
| Contact Info.  | tiji.thomas@oneconvergence.com, @tijithomas                                                       |
| Documentation. | https://docs.dkube.io/unlinked/install2_1/Install-Getting-Started.html               |
| SCM            | https://github.com/oneconvergence             |
| Helm Charts    | https://github.com/oneconvergence/dkube-helm |

- We want to contact with the vendor and ensure they are still interested on having this apps into the catalog.
- If they are interested, work together with them to review the recipes.

📔 There are no updates of this application (in the catalog) in **the last 12 months**.

#### Acceptance criteria

- [x] There is an email thread or GitHub thread (comments) with the vendor
- [x] We have identified a contact person
- [ ] The recipes are updated or deprecated according to their interest.

**Comment by recena** [comment]
@tijithomas Is this product discontinued or deprecated?

**Comment by nflondo** [comment]
Email sent to [tiji.thomas@oneconvergence.com](mailto:tiji.thomas@oneconvergence.com) resulted in "Undeliverable" response.
