### ISSUE TITLE
Health check of Komodor Agent / k8s-watcher

### ISSUE THREAD

**Issue by nflondo** [rancher/partner-charts#924]
This issue aims to perform a health check of this application.

| Attribute      |  Value                                                    |
| -------------- | --------------------------------------------------------- |
| Application    |  Komodor Agent / k8s-watcher |             
| Vendor         |  [Komodor](https://komodor.com/)          |
| Contact Info.  |@nagauker                                                       |
| Documentation. | https://docs.komodor.com/Learn/Komodor-Agent.html               |
| SCM            | https://github.com/komodorio/helm-charts            |
| Helm Charts    | https://github.com/komodorio/helm-charts/tree/master/charts/k8s-watcher |

- We want to contact with the vendor and ensure they are still interested on having this apps into the catalog.
- If they are interested, work together with them to review the recipes.

📔 There are no updates of this application (in the catalog) in **the last 12 months**.

#### Acceptance criteria

- [x] There is an email thread or GitHub thread (comments) with the vendor
- [x] We have identified a contact person
- [x] The recipes are updated or deprecated according to their interest.

**Comment by recena** [comment]
According to the [upstream project](https://github.com/komodorio/helm-charts/tree/master/charts/k8s-watcher#rotating_light-k8s-watcher-helm-chart-deprecation), the Helm Chart is deprecated.

📔 Proposed to be removed.

**Comment by nflondo** [comment]
Done. PR #926
