### ISSUE TITLE
Health check of Tetrate Istio Distro

### ISSUE THREAD

**Issue by nflondo** [rancher/partner-charts#925]
This issue aims to perform a health check of this application.

| Attribute      |  Value                                                    |
| -------------- | --------------------------------------------------------- |
| Application    |  [Tetrate Istio Distro](https://istio.tetratelabs.io/) |             
| Vendor         |  [Tetrate](https://tetrate.io/)          |
| Contact Info.  | tetrate@tetrate.io, @PetrMc, @saptak                                                     |
| Documentation. | https://istio.tetratelabs.io/introduction/               |
| SCM            | https://github.com/tetratelabs           |
| Helm Charts    | https://github.com/tetratelabs/helm-charts |

- We want to contact with the vendor and ensure they are still interested on having this apps into the catalog.
- If they are interested, work together with them to review the recipes.

📔 There are no updates of this application (in the catalog) in **the last 12 months**.

#### Acceptance criteria

- [x] There is an email thread or GitHub thread (comments) with the vendor
- [x] We have identified a contact person
- [ ] The recipes are updated or deprecated according to their interest.

**Comment by nflondo** [comment]
Email sent to: [tetrate@tetrate.io](mailto:tetrate@tetrate.io)

**Comment by saptak** [comment]
@nflondo, we want the recipe to be in the catalog

**Comment by recena** [comment]
@saptak Thank you for your answer. We will give you instructions to keep the recipe updated because at this moment, there are no updates.
