### ISSUE TITLE
Unable to Log In to Harbor UI After Installation via Rancher Manager Apps

### ISSUE THREAD

**Issue by roger-ryao** [rancher/partner-charts#943]
## Describe the bug (🐛 if you encounter this issue)

I installed Harbor using Rancher Manager Apps, but I am unable to log in to the Harbor UI using the default credentials `admin` / `Harbor12345`

## To Reproduce

![Recording 2023-11-09 at 15 42 07](https://github.com/rancher/partner-charts/assets/104337648/557c2f0b-2fb1-4d11-a8ef-b4c91c8e3d66)

## Expected behavior

User could log in to the Harbor UI using the default credentials `admin` / `Harbor12345`

## Log file for troubleshooting

[harbor-portal-8cb4ff958-gj5vg_portal(1).log](https://github.com/rancher/partner-charts/files/13305232/harbor-portal-8cb4ff958-gj5vg_portal.1.log)

## Environment

 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher(v2.8.0-rc3) Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.7 +k3s1 
   - Number of management node in the cluster: 1 
   - Number of worker node in the cluster: 3
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS

## Additional context

N/A

**Comment by nflondo** [comment]
It looks like harbor requires at least [externalURL to be set](https://github.com/goharbor/harbor-helm/issues/565#issuecomment-799132345) during install   

The following worked for me:
1- From Rancher Manager Apps select `Harbor` and click on Install
2- select `Customize Helm options before install` checkbox
3- Edit YAML with:
```
expose:
      tls:
        auto:
          commonName: lab.company.com
      type: nodePort
    externalURL: http://x.x.x.x
```
4- Continue and finish install.
After a few minutes, go to `https://x.x.x.x:30003`  and was able to login with username: admin and password: Harbor12345
