### ISSUE TITLE
/usr/local/bin/partner-charts-ci auto is failing with author field is required

### ISSUE THREAD

**Issue by shanmydell** [rancher/partner-charts#964]
+ curl -s -L -o /usr/local/bin/partner-charts-ci https://github.com/samuelattwood/partner-charts-ci/releases/latest/download/partner-charts-ci-linux-amd64
+ chmod +x /usr/local/bin/partner-charts-ci
+ export PACKAGE=dell/csi-powermax
+ PACKAGE=dell/csi-powermax
+ /usr/local/bin/partner-charts-ci auto
time="2023-12-19T12:53:35-05:00" level=info msg="Parsed dell/csi-powermax\n"
time="2023-12-19T12:53:35-05:00" level=info msg="\n  Source: Git\n  Vendor: Dell\n  Chart: csi-powermax\n  Version: 2.9.0\n  URL: https://github.com/dell/helm-charts.git  \n"
time="2023-12-19T12:53:39-05:00" level=info msg="Cleaning package dell/csi-powermax\n"
time="2023-12-19T12:53:56-05:00" level=info msg="Committing changes"
time="2023-12-19T12:54:33-05:00" level=fatal msg="author field is required"

**Comment by shanmydell** [comment]
@recena: Could you please help us with the above issue?

**Comment by marcosbc** [comment]
@shanmydell I believe it got recently updated as part of #967. Can you confirm everything is fine?

As for the error, it could be caused by your Git client not being fully configured. It should work if you configure your username and email in Git:

```
git config --global user.name "Your Name"
git config --global user.email "your-email@domain.com"
```

**Comment by shanmydell** [comment]
that helped @marcosbc , closing the issue
