### ISSUE TITLE
Partner charts no longer updated?

### ISSUE THREAD

**Issue by hierynomus** [rancher/partner-charts#965]
Hi!

When I was looking at our partner chart in the Rancher marketplace I noticed that it hasn't been updated in a significant time (i.e. 2 months). I thought that happened automatically, using a (daily?) job? Are you aware whether something it broken?

**Comment by nicholasSUSE** [comment]
Hello I am taking the responsibility for `partner-charts` updates now.

**Comment by recena** [comment]
@hierynomus In a few hours, the content will be updated.

**Comment by hierynomus** [comment]
Thanks @recena for picking this up! 👏

**Comment by danielnginx** [comment]
@recena Is the process to update the charts working?

**Comment by recena** [comment]
We have reduced the cadence while we implement a fully automated process.

**Comment by recena** [comment]
@danielnginx It will be updated in a few hours.

**Comment by recena** [comment]
@danielnginx Which app are you waiting to be updated?

**Comment by danielnginx** [comment]
Hi @recena the chart was https://github.com/rancher/partner-charts/tree/main-source/charts/f5/nginx-ingress I can see that is updated now thank you :)

**Comment by danielnginx** [comment]
Hi @recena could you update it again? We release NGINX Ingress Controller on March 26th and it does not seem to be updated on https://github.com/rancher/partner-charts/tree/main-source/charts/f5/nginx-ingress

**Comment by recena** [comment]
@danielnginx Sure.
