### ISSUE TITLE
Add `redis-cluster` to partner-charts

### ISSUE THREAD

**Issue by hungcuongm98** [rancher/partner-charts#992]
- I am working on the enterprise env behind the proxy and prohibited to access github. Could you add the [bitnami/redis-cluster](https://github.com/bitnami/charts/tree/main/bitnami/redis-cluster) to rancher charts

**Comment by recena** [comment]
@hungcuongm98 You can configure a new repository with https://charts.bitnami.com and get all their content.

📚 Rancher Manager [documentation](https://ranchermanager.docs.rancher.com/v2.0-v2.4/how-to-guides/new-user-guides/helm-charts-in-rancher/adding-catalogs#add-private-githelm-chart-repositories) to do it.
